--CORREIOS.RASTREAMENTO_CORREIOS definition

CREATE TABLE "CORREIOS"."RASTREAMENTO_CORREIOS" 
   (	"ID" NUMBER(*,0), 
	"CODIGO_RASTREIO" VARCHAR2(100), 
	"DESCRICAO_GERAL" VARCHAR2(4000), 
	"ENTREGUE" NUMBER(*, 0), 
	"PACOTE_DOS_CLIENTES" NUMBER(*, 0), 
	"DATA_ENCERRAMENTO" DATE, 
	"ULTIMO_PROCESSAMENTO" DATE, 
	"CONTEUDO_PACOTE" VARCHAR2(100), 
	 CONSTRAINT "RASTREAMENTO_CORREIOS_PK" PRIMARY KEY("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "RASTREAMENTO_CORREIOS_UN" UNIQUE("CODIGO_RASTREIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";

CREATE UNIQUE INDEX "CORREIOS"."RASTREAMENTO_CORREIOS_PK" ON "CORREIOS"."RASTREAMENTO_CORREIOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
CREATE UNIQUE INDEX "CORREIOS"."RASTREAMENTO_CORREIOS_UN" ON "CORREIOS"."RASTREAMENTO_CORREIOS" ("CODIGO_RASTREIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";